name: progress_form
description: "Simple form app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  foundation:
    path: packages/foundation   
  go_router: ^14.2.7
  provider: ^6.1.2
  path_provider: ^2.1.4
  flex_color_scheme: ^7.3.1
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"